AllCops:
  Exclude:
  - data/**/*

ClassAndModuleChildren:
  Enabled: false

Documentation:
  Exclude:
  - spec/**/*

TrivialAccessors:
  AllowPredicates: true

# TODO: Isn't this already default?
LineLength:
  Max: 80
