AllCops:
  Exclude:
  - data/**/*
  - spec/fixtures/**/*

Metrics/AbcSize:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true

Style/Documentation:
  Exclude:
  - spec/**/*
